# services/content_fetchers/youtube_fetcher.py
"""
youtube_fetcher.py
==================

Fetches video metadata and comments from YouTube.
"""


import os
import sys
import json
import re
import subprocess
from datetime import datetime, timezone
from pprint import pprint
from dataclasses import asdict
import shutil

from enums.platform_enum import PlatformEnum
from services.content_fetchers.base_fetcher import ContentFetcher
from models.content_models import ContentAnalysis, Comment, ContentItem


##################################################################
class YouTubeFetcher(ContentFetcher):
    """Fetches content from YouTube using the YouTube Data API."""

    # ----------------------------------------------------------------
    def can_handle(self, url: str) -> bool:
        """Check if URL is a YouTube URL."""
        return "youtube.com" in url or "youtu.be" in url

    # ----------------------------------------------------------------
    def fetch_content(self, url: str, progress_callback=None) -> ContentAnalysis:
        """
        Fetch YouTube video metadata and comments using yt-dlp,
        saving them as timestamped JSON files inside Content_Archive.
        
        Args:
            url: YouTube video URL
            progress_callback: Optional callback function(percent, status) for progress updates
        """
        platform = "youtube"
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H-%M-%S")

        # Base directory for all YouTube content
        base_dir = os.path.join("Content_Archive", platform)
        os.makedirs(base_dir, exist_ok=True)

        # Temporary directory used before we identify the channel
        temp_dir = os.path.join(base_dir, "_temp")
        os.makedirs(temp_dir, exist_ok=True)

        # Start with the temp directory as output (we don't yet know channel_id)
        output_template = os.path.join(temp_dir, f"{timestamp}_%(id)s_%(title)s")


        command = [
            "yt-dlp",
            "--skip-download",
            "--write-info-json",
            "--cookies-from-browser", "chrome",            # Authenticate via Chrome session
            "--write-comments",
            "--extractor-args", "youtube:comment_sort=top",
            "--extractor-args", "youtube:max_comments=all,all,all,all",
            "--sleep-requests", "1",                       # Pause 1s between HTTP requests
            "--limit-rate", "3M",                          # Max transfer rate
            "-o", output_template,
            url,
        ]

        # Running yt-dlp with real-time output
        print(f"Running yt-dlp for {url} ...")
        try:
            process = subprocess.Popen(
                command,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,  # Merge stderr into stdout
                text=True,
                bufsize=1,  # Line buffered
                universal_newlines=True
            )
            
            # Read output line by line
            for line in process.stdout:
                line = line.strip()
                
                # Print for debugging
                print(line)
                
                # Parse progress if callback provided
                if progress_callback and line:
                    # yt-dlp progress format: [download]  45.2% of 1.23MiB at 500.00KiB/s ETA 00:02
                    match = re.search(r'\[download\]\s+(\d+\.?\d*)%', line)
                    if match:
                        percent = float(match.group(1))
                        progress_callback(percent, line)
            
            # Wait for completion
            return_code = process.wait()
            
            if return_code != 0:
                raise RuntimeError(f"yt-dlp failed with exit code {return_code}")
                
        except Exception as e:
            raise RuntimeError(f"yt-dlp failed: {e}") from e

        # Locate the generated JSON in temp_dir
        # CONCURRENCY ISSUE HERE - This code should not run in parallel
        json_files = [f for f in os.listdir(temp_dir) if f.endswith(".info.json")]
        if not json_files:
            raise FileNotFoundError("No JSON file generated by yt-dlp.")
        json_path = os.path.join(temp_dir, json_files[-1])

        # Load JSON into memory now that you know it exists
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        channel_id = data.get("channel_id") or data.get("uploader_id") or "unknown_channel"
        channel_name = data.get("channel") or data.get("uploader") or "unknown_name"
        safe_channel_name = "".join(c if c.isalnum() or c in " _-" else "_" for c in channel_name)

        # Build and create the actual channel directory
        channel_dir = os.path.join(base_dir, f"{safe_channel_name}_{channel_id}")
        os.makedirs(channel_dir, exist_ok=True)

        # Move the JSON from the temp folder into the proper channel folder
        final_json_path = os.path.join(channel_dir, os.path.basename(json_path))
        shutil.move(json_path, final_json_path)

        print(f"Saved combined metadata and comments to {final_json_path}")

        # Parsing the document into ContentAnalysis model:
        analysis = self._map_to_models(data)
        print(f"Mapped video '{analysis.content.title}' with {len(analysis.comments)} comments.")

        return analysis

    # ----------------------------------------------------------------
    def _map_to_models(self, data: dict) -> ContentAnalysis:
        """Convert yt-dlp JSON into our internal ContentAnalysis model."""

        # Convert upload_date ("YYYYMMDD") to ISO 8601 (e.g., "2025-10-26T00:00:00Z")
        published_at = None
        if upload_date := data.get("upload_date"):
            try:
                published_at = datetime.strptime(upload_date, "%Y%m%d").date().isoformat()
            except ValueError:
                published_at = None

        # Youtube Video as ContentItem
        content = ContentItem(
            content_id=data.get("id", ""),
            platform=PlatformEnum.YOUTUBE,
            url=data.get("webpage_url", ""),
            title=data.get("title", "Untitled"),
            author=data.get("uploader") or data.get("channel", "Unknown"),
            description=data.get("description"),
            published_at=published_at,
            view_count=data.get("view_count"),
            like_count=data.get("like_count"),
            comment_count=data.get("comment_count"),
        )

        # Comments
        comments = []
        for c in data.get("comments", []):
            # Convert timestamp to ISO 8601
            published_iso = None
            if ts := c.get("timestamp"):
                published_iso = (
                    datetime.fromtimestamp(ts, tz=timezone.utc)
                    .isoformat()
                    .replace("+00:00", "Z")
)

            comments.append(
                Comment(
                    comment_id=c.get("id", ""),
                    content_id=data.get("id", ""),
                    author=c.get("author", "Unknown"),
                    text=c.get("text", ""),
                    published_at=published_iso or "",
                    like_count=c.get("like_count", 0),
                    reply_count=0,
                    parent_comment_id=None if c.get("parent") == "root" else c.get("parent"),
                )
            )

        # Return
        return ContentAnalysis(content=content, comments=comments)

    # ----------------------------------------------------------------

##################################################################

def main():
    """Main"""
    default_url = "https://www.youtube.com/watch?v=hSXQg2IQ3QM&t=627s"

    # Optionally allow URL override from command line
    url = sys.argv[1] if len(sys.argv) > 1 else default_url

    print(f"Fetching content for: {url}")

    fetcher = YouTubeFetcher()

    # Progress handler that prints updates
    def progress_handler(percent, status_line):
        # Print progress with carriage return to overwrite same line
        print(f"\rProgress: {percent:5.1f}% - {status_line}", end='', flush=True)

    try:
        result = fetcher.fetch_content(url, progress_callback=progress_handler)
        print()  # New line after progress completes
    except Exception as e:
        print(f"\nError occurred while fetching content: {e}")
        sys.exit(1)

    print("Fetch completed successfully!")
    print("\n=== ContentItem Metadata ===")
    # Print all fields of the ContentItem
    pprint(asdict(result.content))

    print("\n=== Sample Comments (up to 3) ===")
    for c in result.comments[:3]:
        pprint(asdict(c))
        print("--")

    print(f"\nTotal comments fetched: {len(result.comments)}")


if __name__ == "__main__":
    main()
